export const careMemberConsts = {
    REQUEST_CARE_MEMBERS_PENDING: 'REQUEST_CARE_MEMBERS_PENDING',
    REQUEST_CARE_MEMBERS_SUCCESS: 'REQUEST_CARE_MEMBERS_SUCCESS',
    ADD_CARE_MEMBER_PENDING: 'ADD_CARE_MEMBER_PENDING',
    ADD_CARE_MEMBER_SUCCESS: 'ADD_CARE_MEMBER_SUCCESS',
    ADD_CARE_MEMBER_FAILED: 'ADD_CARE_MEMBER_FAILED',
    UPDATE_CARE_MEMBER_PENDING: 'UPDATE_CARE_MEMBER_PENDING',
    UPDATE_CARE_MEMBER_SUCCESS: 'UPDATE_CARE_MEMBER_SUCCESS',
    UPDATE_CARE_MEMBER_FAILED: 'UPDATE_CARE_MEMBER_FAILED'
};