export const userConsts = {
    VALIDATE_USER_PENDING: 'VALIDATE_USER_PENDING',
    VALIDATE_USER_SUCCESS: 'VALIDATE_USER_SUCCESS',
    VALIDATE_USER_FAILED: 'VALIDATE_USER_FAILED',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS'
};